name: Deploy to Pages

on:
  push:
    branches:    
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: npm run build
      - name: copy files to dist
        run: |
          cd dist
          rm -r *
          cd ../build
          cp -fr . ../dist
      - name: commit dist
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Greg
          author_email: gkap720@gmail.com
          message: "Deploy"
          cwd: './dist'  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
