name: Deploy to Pages

on:
  push:
    branches:    
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-modules
      - name: Install modules
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install
      - run: CI=false npm run build
      - name: Delete files in dist
        run: |
          cd dist
          ls -la
        shell: bash
      - name: Copy files to dist
        run: |
          cd build
          cp -fr . ../dist
          cd ../dist
          ls -la
      - name: commit dist
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Greg
          author_email: gkap720@gmail.com
          message: "Deploy"
          cwd: './dist'
          ref: 'gh-pages'  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
