# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm run build
      - name: copy files to dist
        run: |
          cd dist
          rm -r *
          cd ../build
          cp -fr . ../dist
      - name: commit dist
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Greg
          author_email: gkap720@gmail.com
          message: "Deploy"
          cwd: './dist'  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
